<CrossValidationBlock>:
	title: 'Cross Validation'
	block_color: root.b.MODEL_SELECTION.value
	data_input: data_input
	estimator_input: estimator_input
	cross_val_input: cross_val_input
	cross_out: cross_out
	# Inputs
	InputPin:
		id: data_input
		_type: root.t.DATAFRAME
	InputPin:
		id: estimator_input
		_type: root.t.CLASSIFICATOR
	InputPin:
		id: cross_val_input
		_type: root.t.CROSS_VALIDATOR
	# Outputs
	OutputPin:
		id: cross_out
		_type: root.t.STR

