<TenFoldBlock>:
	in_1: in_1
	out_1: out_1
	block_label: '10-fold'
	block_color: .133, .4, .4, 1
	FloatLayout:
		id: content
		EmptyContent:
			pos: content.pos
			CircularButton:
				id: in_1
				block: root
				size_hint: None, None
				size: '10dp', '10dp'
				x: content.x + 5
				y: content.y + content.height / 2
			CircularButton:
				id: out_1
				block: root
				size_hint: None, None
				size: '10dp', '10dp'
				x: content.x + content.width - 10 - 5
				y: content.y + content.height / 2
