#:import SVC sklearn.svm.SVC
#:import KFold sklearn.model_selection.KFold
#:import StratifiedKFold sklearn.model_selection.StratifiedKFold
#:import RandomForestClassifier sklearn.ensemble.RandomForestClassifier
#:import KNeighborsClassifier sklearn.neighbors.KNeighborsClassifier


PrototypeScreen:

<PrototypeScreen>:
	text_input_train_file: text_input_train_file.text
	orientation: 'horizontal'
	spacing: '15dp'
	padding: '15dp'
	BoxLayout:
		orientation: 'vertical'
		padding: '15dp'
		spacing: '15dp'
		BoxLayout:
			orientation: 'vertical'
			spacing: '5dp'
			TextInput:
				id: text_input_train_file
				size_hint_y: None
				height: '30dp'
				multiline: False
				on_focus: root.load_popup(self)
			Button
				text: 'Load File'
				on_release: root.load_popup(text_input_train_file)
		ToggleButton:
			text: 'SVM'
			group: 'estimators'
			on_release: app.estimator = SVC()
		ToggleButton:
			text: 'K Nearest Neighbors'
			group: 'estimators'
			on_release: app.estimator = KNeighborsClassifier()
		ToggleButton:
			text: 'Random Forest'
			group: 'estimators'
			on_release: app.estimator = RandomForestClassifier()
	BoxLayout:
		orientation: 'vertical'
		spacing: '15dp'
		ToggleButton:
			text: '50/50 split'
			group: 'cv'
			on_release: app.cv = KFold(n_splits=2)
		ToggleButton:
			text: '3-folds'
			group: 'cv'
			on_release: app.cv = None
		ToggleButton:
			text: '10-folds (Stratified)'
			group: 'cv'
			on_release: app.cv = StratifiedKFold(n_splits=10)
	BoxLayout:
		orientation: 'vertical'
		Button:
			text: 'Validate'
			size_hint_y: 20
			on_release: root.validate()
		Label:
			size_hint_y: 60
			text: root.result
		BoxLayout:
			orientation: 'vertical'
			size_hint_y: 20
			spacing: '5dp'
			TextInput:
				on_focus: root.load_popup(self)
			Button:
				text: 'Predict'
				on_release: app.predict()

<LoadDialog>: # A file chooser dialog (Popup)
	load_button: load_button
	selected_file: filechooser.selection and filechooser.selection[0] or ''
	BoxLayout:
		pos: root.pos
		orientation: 'vertical'
		FileChooserIconView:
			id: filechooser
			filters: ['*.csv']
			path: '~'
			on_selection: root.toggle_load_button(self.selection)
			on_submit: root.dismiss()
		TextInput:
			id: current_file
			text: root.selected_file
			size_hint_y: None
			height: '30dp'
			multiline: False
		BoxLayout:
			orientation: 'horizontal'
			size_hint_y: None
			height: '30dp'
			Button:
				text: 'Cancel'
				on_release: root.dismiss()
			Button:
				id: load_button
				disabled: True
				text: 'Load'
				on_release: root.dismiss()

